-- AlterTable
ALTER TABLE "Bet" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Game" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Participant" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
